---
name: Publish

"on":
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: |
          yarn install --frozen-lockfile
      # - name: Lint
      #   run: |
      #     npm run lint
      # - name: Test
      #   run: |
      #     npm test
      - name: Push release to npm (public)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          yarn publish --access public .
